### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by aborovsky** [PaulAvery/node-jrpc-schema#2]
Error parsing JSON in routine Schema.prototype.handleResponse.
There is absolutely no error handling.
Stack trace:

```
31 Jan 13:08:41 - SyntaxError: Unexpected token �
    at Object.parse (native)
    at Schema.handleResponse (/Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/jrpc-schema/lib/Schema.js:78:20)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/WebSocket.js:797:10)
    at /Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/Receiver.js:360:5)
    at /Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.1.finish (/Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/Receiver.js:478:12)
    at Receiver.expectHandler (/Users/boba/Documents/Work/@beetoo_nodered/beetoo-node-red/node_modules/ws/lib/Receiver.js:453:31)
```

How about to add try..catch for JSON.parse inside of Schema.prototype.handleResponse function?

**Comment by UhhhWaitWhat** [comment]
I think it might be a better idea to let the wrapping code catch that?
Something like

``` js
try {
    root.handleResponse()
} catch(e) {
    /* Do something */
}
```

Mainly because I have no idea what to do with the error. We could emit it on the root object, but I am not sure if that makes any sense because we currently do not use it as an emitter. We cant reject a handler because we dont know which method the response belongs to. So I think the calling code should try to catch anything going wrong here.

I am open to suggestions though, in case you have a better idea.

**Comment by aborovsky** [comment]
Yes, you absolutely right.
Ant thank you for this commit:
https://github.com/PaulAvery/kodi-ws/commit/3e85b3be60c96907e8d73da427ec62ee9580cd66

вс, 31 янв. 2016 г. в 15:42, Florian Albertz notifications@github.com:
